version: '3.9'
services:
  commit-viewer-app:
    container_name: commit-viewer-app
    build:
      context: ../..
      dockerfile: infra/commit-viewer/Dockerfile
    image: commit-viewer-app:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - commit-viewer-network
  database:
    container_name: database
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=commit_viewer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - ALLOW_IP_RANGE='0.0.0.0/0'
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - commit-viewer-network
networks:
  commit-viewer-network:
    name: commit-viewer-network